### ISSUE TITLE
Event Handler Bypassing

### ISSUE THREAD

**Issue by brandonhardingj** [nwnxee/unified#47] opened 2018-02-13 18:25 UTC
It'd be helpful to have a means of bypassing an event handler. My specific thought is in regards to the examine, with my current intent being to simply skip the examining and instead giving the player a message in their combat log. 

However, wherever this idea can apply works for me!

**Comment by Liareth** [comment] 2018-03-09 09:36
Duplicate of https://github.com/nwnxee/unified/issues/16

**Closed by Liareth** 2018-03-09 09:36 UTC
