### ISSUE TITLE
[Bug] - NWNX_Dialog_SetCurrentNodeText

### ISSUE THREAD

**Issue by FrogsOfDoom** [nwnxee/unified#520] opened 2019-06-24 03:01 UTC
Hi,

I've noticed a bug with NWNX_Dialog_SetCurrentNodeText. Specifically when trying to insert color tokens (ie: <c  ></c>), I get unrecognized tokens when using this function. Other tokens (ie: StartHighlight, StartAction) work fine and I double checked by sending as a message the same content and the color works then. These color tokens also work when set up as a text token (CUSTOM***) but not with this function.

Hope that helps.

Thanks

**Comment by Aschent89** [comment] 2020-04-23 20:32
Notating that I also experienced this bug. As the OP mentioned, StartHighlight and StartAction both function as expected, however color codes from: https://colortoken.nwn1.net/ do not function as intended.

![image](https://user-images.githubusercontent.com/42368518/80146438-b2bb5000-8566-11ea-8e39-e35022d8dc51.png)

Color Code used: string ORANGE     = "<cþ} >"
Color Code close: "</c>"

Color codes in conversations have previously worked when using scripted conversations in the past with zzdlg.

**Comment by plenarius** [comment] 2020-11-14 11:11
The `NWNX_Dialog_SetCurrentNodeText` works pretty much how the toolset conversation editor works, you can't use custom colour tokens. zzdlg got around this by wrapping all text in custom tokens which should do the trick here too. Something like below might work? 

```c
const int BASE_TOKEN_FOR_DIALOG_TEXTS = 4201;

void MySetCurrentNodeText(string sText)
{
    int iToken = BASE_TOKEN_FOR_DIALOG_TEXTS + NWNX_Dialog_GetCurrentNodeIndex();
    SetCustomToken(iToken, sText);
    NWNX_Dialog_SetCurrentNodeText("<CUSTOM"+IntToString(iToken)+">");
}
```

**Comment by plenarius** [comment] 2020-11-23 06:25
Closing, not really an issue with nwnx and a viable method to achieve the end result has been proposed.

**Closed by plenarius** 2020-11-23 06:25 UTC
Labels: bug, not an issue, wontfix
